apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
        - name: {{APP_NAME}}
          image: {{IMAGE_FULL_TAG}}
          ports:
            - containerPort: {{CONTAINER_PORT}}
              # hostPort: 80 # To allow deployment to be accessed via port 80 explicitly for testing
              # protocol: TCP
          env:
            - name: NODE_ENV
              value: production
            - name: MICROSERVICE_NAME
              value: Qualisoft Microservice
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: qualisoft-secret
                  key: DATABASE_URL
            - name: ROOT_PATH
              value: /{{APP_ROUTE}}
            - name: AUTH_API
              value: http://192.168.12.170/luminess-ad-authentication-microservice
            - name: GPAO_API
              value: http://192.168.12.170/gpao-microservice
            - name: RBAC_API
              value: http://192.168.12.170/luminess-rbac-microservice
          #     valueFrom:
          #       secretKeyRef:
          #         name: {{APP_SECRET_NAME}}
          #         key: api-key
      # nodeSelector:
      #   frontend-host: true
      imagePullSecrets:
        - name: regcred # Use this secret to pull the image from the local registry