apiVersion: v1
kind: Secret
metadata:
  name: qualisoft-secret
  namespace: luminess-microservice # Assurez-vous que l'espace de noms est correct
type: Opaque
data:
  # La valeur doit être la chaîne encodée en base64
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQDE5Mi4xNjguMTIuMjMyOjU0MzIvZGJfcXVhbGl0ZQ==